var fs=require('fs')
fs.writeFileSync('hello.txt',"Good morning")
fs.appendFileSync('hi.txt',"\nToday's date is 13th March 2026")
var data=fs.readFileSync('hello.txt',"utf-8")
//console.log(data)
fs.renameSync("hello.txt","B3.txt")
fs.unlinkSync('hi.txt')
var data1=fs.readFileSync('B3.txt','utf-8')
console.log(data1)